# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080

# ===============================
# DATABASE CONFIGURATION (Supabase)
# ===============================
# IMPORTANT: It is highly recommended to use the Transaction Pooler URL (.pooler.supabase.com) 
# instead of the direct URL (db.*.supabase.co) for Spring Boot to avoid IPv6 timeout errors.
# Replace [YOUR-PASSWORD] with your actual Supabase password.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
# ===============================
# EXTERNAL APIs
# ===============================
nasa.api.key=${NASA_API_KEY}

# ===============================
# JPA / HIBERNATE
# ===============================
# 'update' automatically updates your tables based on your Java Record/Entity classes but create will actually create it
# CHANGE THIS TO UPDATE LATER
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# LOGGING
# ===============================
logging.level.root=INFO

